package constants

var Coats = []string{"bay", "black", "chestnut", "gray", "dark bay"}

var TalentRarity = []string{"none", "common", "rare", "epic", "legendary"}

var BreedingType = []string{"A", "AA", "B", "BB"}

var SourceHorseNames = []string{
	"Iroquois",
	"Sysonby",
	"Henry Of Navarre",
	"Domino",
	"Hamburg",
	"Man Of War",
	"Colin",
	"Rock View",
	"Regret",
	"Zev",
	"Exterminator",
	"Sir Barton",
	"Sun Briar",
	"Sweep",
	"Billy Kelly",
	"Gallant Fox",
	"War Admiral",
	"Equipoise",
	"Twenty Grand",
	"Seabiscuit",
	"Whirlaway",
	"Alsab",
	"Citation",
	"Count Fleet",
	"Assault",
	"Stymie",
	"Pensive",
	"Nashua",
	"Swaps",
	"Sword Dancer",
	"Tom Fool",
	"Round Table",
	"Dr Fager",
	"Buckpasser",
	"Damascus",
	"Arts And Letters",
	"Affirmed",
	"Seattle Slew",
	"Spectacular Bid",
	"Alydar",
	"Steve Cauthen",
	"Ferdinand",
	"Alysheba",
	"Sunday Silence",
	"Easy Goer",
	"Cigar",
	"Bargain Blitz",
	"Protester",
	"Pheonix",
	"Cordlace",
	"Bart",
	"Night Sky",
	"Hole In One",
	"Anchor",
	"Red Tape",
	"Alkimos",
	"Gold Digger",
	"Volume One",
	"Harry The Fox",
	"Tambourine",
}
